spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reflectionsdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: teste
    password: teste
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect